//! Auth header dispatch for the OpenAI Responses egress.
//!
//! Three auth_kind variants:
//!
//! - `ChatgptOauth`: the ChatGPT subscription surface at
//!   `https://chatgpt.com/backend-api/codex`. Injects only the auth
//!   pair:
//!   ```text
//!   Authorization: Bearer <jwt>
//!   ChatGPT-Account-Id: <uuid>   (when cfg.account_id is Some)
//!   ```
//!   The codex CLI identity / client headers (originator,
//!   residency, version, session-id, installation-id) are no longer
//!   constructed here. Operators supply them through `header_extras`
//!   in config; the per-request `thread-id` / `x-client-request-id`
//!   and the per-provider `x-codex-window-id` are generated by the
//!   provider's `build_headers` on the ChatgptOauth path.
//!
//! - `ApiKey`: the standard OpenAI surface at
//!   `https://api.openai.com/v1/responses`. Injects only
//!   `Authorization: Bearer <api_key>` -- ChatGPT-Account-Id is
//!   ChatGPT-OAuth-specific and absent here. Operators needing
//!   `OpenAI-Organization` / `OpenAI-Project` set them via
//!   `header_extras`.
//!
//! - `BedrockMantle`: the Mantle proxy at
//!   `https://bedrock-mantle.<region>.api.aws/openai/v1`. Authorization:
//!   Bearer <bearer> using the long-term Bedrock API key (resolved via
//!   api_key_ref, typically env://AWS_BEARER_TOKEN_BEDROCK).

use reqwest::RequestBuilder;

use routectl_core::Result;
use routectl_core::identity::codex::codex_user_agent;

use super::{AuthKind, OpenAiResponsesConfig};

/// Default `User-Agent` for the ChatGPT-OAuth surface. Operator-supplied
/// `cfg.user_agent` wins when set; otherwise we emit codex CLI's UA shape
/// (`codex_cli_rs/<X.Y.Z> (<os_type> <os_version>; <arch>) <terminal>`).
/// This is the client-level fallback until the operator sets
/// `user_agent` in config.
pub(crate) fn default_user_agent() -> String {
    codex_user_agent().to_string()
}

/// Apply auth headers to an in-flight `RequestBuilder` per
/// `cfg.auth_kind`. The bearer is resolved by the caller (once per
/// upstream request via `cfg.auth.token().await`) and passed in here
/// so a routectl-managed OAuth source can rotate without a daemon
/// restart. Returns the modified builder.
pub(crate) fn apply(
    rb: RequestBuilder,
    cfg: &OpenAiResponsesConfig,
    bearer: &str,
) -> Result<RequestBuilder> {
    match cfg.auth_kind {
        AuthKind::ChatgptOauth => Ok(apply_chatgpt_oauth(rb, cfg, bearer)),
        AuthKind::ApiKey | AuthKind::BedrockMantle => Ok(apply_api_key(rb, bearer)),
    }
}

/// ChatGPT-OAuth auth injection: `Authorization: Bearer <jwt>` plus
/// `ChatGPT-Account-Id` when configured. Nothing else. The codex
/// identity / client headers now flow through `header_extras`
/// (operator-configured) or per-request generation in the provider's
/// `build_headers`.
///
/// User-Agent is set at the reqwest::Client level (client-level
/// default header) via `http_client::build` in
/// `OpenAiResponsesProvider::new()`, matching the anthropic_api
/// pattern.
fn apply_chatgpt_oauth(
    rb: RequestBuilder,
    cfg: &OpenAiResponsesConfig,
    bearer: &str,
) -> RequestBuilder {
    let mut rb = rb.header("authorization", format!("Bearer {bearer}"));
    if let Some(account_id) = cfg.account_id.as_deref() {
        rb = rb.header("ChatGPT-Account-Id", account_id);
    }
    rb
}

/// Standard OpenAI API-key header injection for the public
/// `api.openai.com/v1/responses` endpoint. Only `Authorization: Bearer
/// <api_key>` is required; `ChatGPT-Account-Id` is ChatGPT-OAuth-
/// specific and intentionally absent. The factory's
/// `validate_openai_responses_account_id` already rejects an
/// `account_id_ref` paired with `auth_kind = "api-key"`, so we never
/// see `cfg.account_id` set on this path. User-Agent is set at the
/// client level (mirrors the chatgpt-oauth path). The bearer is
/// resolved by the caller and passed in (see `apply`).
fn apply_api_key(rb: RequestBuilder, bearer: &str) -> RequestBuilder {
    rb.header("authorization", format!("Bearer {bearer}"))
}

#[cfg(test)]
mod tests {
    use super::*;
    use reqwest::Client;
    use routectl_core::identity::codex::{CODEX_ORIGINATOR, PINNED_CODEX_VERSION};
    use routectl_core::{StaticToken, TokenSource};
    use std::sync::Arc;

    fn base_cfg(auth_kind: AuthKind) -> OpenAiResponsesConfig {
        OpenAiResponsesConfig {
            id: "openai-responses:test".into(),
            auth: Arc::new(StaticToken::new("test-jwt")) as Arc<dyn TokenSource>,
            account_id: Some("acct-uuid".into()),
            base_url: "https://chatgpt.com/backend-api/codex".into(),
            auth_kind,
            header_extras: Vec::new(),
            user_agent: None,
            session_id: None,
        }
    }

    /// Pull a single header value out of a built `reqwest::Request`,
    /// case-insensitively (reqwest lowercases header names internally).
    fn header(req: &reqwest::Request, name: &str) -> Option<String> {
        req.headers()
            .get(name)
            .and_then(|v| v.to_str().ok())
            .map(str::to_string)
    }

    /// On the ChatgptOauth path, `apply` injects ONLY the auth pair:
    /// `Authorization: Bearer <jwt>` + `ChatGPT-Account-Id`. The codex
    /// identity / client headers (originator, residency, version,
    /// session-id, installation-id, window-id, thread-id,
    /// x-client-request-id) are no longer constructed here -- they flow
    /// through `header_extras` or per-request generation in the
    /// provider's `build_headers`.
    #[test]
    fn chatgpt_oauth_injects_only_bearer_and_account_id() {
        // Arrange
        let cfg = base_cfg(AuthKind::ChatgptOauth);
        let client = Client::new();
        let rb = client.post("https://chatgpt.com/backend-api/codex/responses");

        // Act
        let rb = apply(rb, &cfg, "test-jwt").expect("apply");
        let req = rb.build().expect("build");

        // Assert: exactly the auth pair is present.
        assert_eq!(
            header(&req, "authorization").as_deref(),
            Some("Bearer test-jwt")
        );
        assert_eq!(
            header(&req, "chatgpt-account-id").as_deref(),
            Some("acct-uuid")
        );

        // Assert: NOTHING ELSE. Every codex identity / fingerprint
        // header that auth.rs used to inject must now be absent.
        for absent in [
            "originator",
            "x-openai-internal-codex-residency",
            "version",
            "session-id",
            "x-codex-installation-id",
            "x-codex-window-id",
            "thread-id",
            "x-client-request-id",
        ] {
            assert!(
                header(&req, absent).is_none(),
                "{absent:?} must not be injected by apply_chatgpt_oauth anymore",
            );
        }
        // Per-request UA absent (client-level only).
        assert!(
            header(&req, "user-agent").is_none(),
            "UA should not be set as a per-request header"
        );
    }

    #[test]
    fn user_agent_starts_with_codex_cli_rs() {
        // Arrange + Act
        let ua = default_user_agent();

        // Assert: codex-style UA prefix and pinned version.
        assert!(
            ua.starts_with(&format!("{CODEX_ORIGINATOR}/{PINNED_CODEX_VERSION}")),
            "unexpected UA string: {ua}"
        );
        assert!(
            ua.contains(std::env::consts::ARCH),
            "UA should contain arch {} but was: {ua}",
            std::env::consts::ARCH,
        );
    }

    #[test]
    fn api_key_auth_headers_inject_bearer_only() {
        // Arrange: ApiKey carries no account_id_ref by config-time
        // invariant (factory rejects the combination).
        let mut cfg = base_cfg(AuthKind::ApiKey);
        cfg.account_id = None;
        let client = Client::new();
        let rb = client.post("https://api.openai.com/v1/responses");

        // Act: the caller resolves the bearer from `cfg.auth` and
        // passes it in; `apply_api_key` no longer reads the config.
        let rb = apply(rb, &cfg, "sk-test-123").expect("apply");
        let req = rb.build().expect("build");

        // Assert: Bearer auth present; ChatGPT-OAuth-specific headers
        // (ChatGPT-Account-Id, identity headers) are absent.
        assert_eq!(
            header(&req, "authorization").as_deref(),
            Some("Bearer sk-test-123")
        );
        for absent in [
            "chatgpt-account-id",
            "originator",
            "version",
            "session-id",
            "x-codex-installation-id",
            "x-codex-window-id",
            "thread-id",
            "x-client-request-id",
            "x-openai-internal-codex-residency",
        ] {
            assert!(
                header(&req, absent).is_none(),
                "{absent:?} must not be set for api-key",
            );
        }
        // Per-request UA absent (client-level only).
        assert!(
            header(&req, "user-agent").is_none(),
            "UA should not be set as a per-request header"
        );
    }

    #[test]
    fn bedrock_mantle_auth_injects_bearer() {
        // Arrange: BedrockMantle carries no account_id_ref by config-time
        // invariant (factory rejects the combination). The bearer is the
        // long-term AWS Bedrock API key (typically resolved from
        // env://AWS_BEARER_TOKEN_BEDROCK by the caller).
        let mut cfg = base_cfg(AuthKind::BedrockMantle);
        cfg.account_id = None;
        let client = Client::new();
        let rb = client.post("https://bedrock-mantle.us-east-2.api.aws/openai/v1/responses");

        // Act: byte-identical Bearer auth to the api-key path.
        let rb = apply(rb, &cfg, "bedrock-bearer-xyz").expect("apply");
        let req = rb.build().expect("build");

        // Assert: Bearer auth present; ChatGPT-OAuth-specific headers
        // (ChatGPT-Account-Id, identity headers) are absent.
        assert_eq!(
            header(&req, "authorization").as_deref(),
            Some("Bearer bedrock-bearer-xyz")
        );
        for absent in [
            "chatgpt-account-id",
            "originator",
            "version",
            "session-id",
            "x-codex-installation-id",
            "x-codex-window-id",
            "thread-id",
            "x-client-request-id",
            "x-openai-internal-codex-residency",
        ] {
            assert!(
                header(&req, absent).is_none(),
                "{absent:?} must not be set for bedrock-mantle",
            );
        }
        // Per-request UA absent (client-level only).
        assert!(
            header(&req, "user-agent").is_none(),
            "UA should not be set as a per-request header"
        );
    }
}
