//! The CLOAK BASELINE weld: the credential-lane transform enumeration, welded
//! to the module surface where a derived side honestly exists and pinned by a
//! named register where it does not.
//!
//! Two tiers, and the ASYMMETRY between them is the first thing to read. It is
//! not an accident of effort -- it is the boundary between a population a
//! machine can enumerate and one only a reader can.
//!
//! # Tier 1 -- the in-module transforms, DERIVED and welded
//!
//! `anthropic_api/cloak.rs` plus the flat `anthropic_api/cloak/*.rs` are one
//! bounded surface, so the eligible items in them can be derived from a parse
//! (see `weld_support/cloak_population.rs` for the eligibility rule) and
//! compared against [`TIER_ONE`] by OCCURRENCE COUNT. That comparison is real
//! in both directions: an item added to the surface without joining the
//! register is red, and a register row whose item left the surface is red.
//!
//! ## What tier 1 adds over the compiler, and what it does not
//!
//! The compiler is still the pin for two of the three failure shapes. Delete a
//! transform and `cloak_oauth_egress` stops compiling; add one and never wire
//! it and `dead_code` fires. Neither of those needs a weld, and this weld does
//! not claim them.
//!
//! Its residual job is the ONE shape the compiler is blind to: a function that
//! is both ADDED and WIRED into the live path, which is neither dead nor
//! required by anything to join a hand-authored enumeration. That is the whole
//! ceiling of tier 1, and the internal baseline register restates it in the same
//! terms.
//!
//! Two structural choices follow from that job:
//!
//! - `cloak.rs` itself is IN the population, and its eligible non-transform
//!   items are classified as support/orchestrator in the same register. A
//!   population drawn from the leaf directory alone would let a transform
//!   written inline beside the orchestrator evade the weld entirely -- which is
//!   the easiest place to add one.
//! - the comparison is over occurrence COUNTS, not sets. A set absorbs a row
//!   listed twice and still looks complete, which is how one item can be
//!   classified under two contradictory reasons with nothing red.
//!
//! ## What tier 1 refuses rather than covers
//!
//! An item whose body a parse cannot see is refused, never skipped: any
//! item-position macro invocation, a `cfg_attr` that could inject a gate or a
//! path, an eligible function-pointer `const` or `static`. That last one is a
//! standing CEILING rather than a gap to close: a transform held in a value slot
//! is callable without being a function item, and following value initializers
//! through arbitrary expressions is a different program. Items generated by a
//! `derive` are outside the population by construction, for the same reason --
//! the derivation reads source before expansion.
//!
//! # Tier 2 -- the out-of-module transforms, CLAIMED and pinned, with no derived side
//!
//! The rest of the credential lane's transforms live in other modules and
//! another crate, each on its own gate predicate. There is no honest
//! tree-to-register derived side for them, and [`TIER_TWO`] does not pretend
//! otherwise: "every credential-lane transform wherever it lives" is a SEMANTIC
//! predicate, not a syntactic one. No parse decides whether a body or header
//! mutation is part of the cloak baseline.
//!
//! So what tier 2 enforces is the direction that IS checkable: every row it
//! claims is real -- its anchor resolves to a named item in the file it names,
//! its gate is in a closed vocabulary, its reason is checkable, and its pinning
//! test exists. It CANNOT prove no row is missing, and the register must never
//! be read as if it could.
//!
//! A partial scan of the lane-predicate call sites was considered as a derived
//! side and rejected: it would miss both new work inside an existing gate and
//! every always-on transform, while reading as completeness -- which is worse
//! than an honest absence, because a reader stops re-deriving what looks
//! already derived.
//!
//! `cloak_oauth_egress` itself is deliberately untouched by all of this. Its
//! transform order is load-bearing (the tool sort runs LAST so it orders the
//! final wire names) and its shapes are fixed from empirical capture, so the
//! enumeration is welded from the OUTSIDE rather than turned into a value the
//! live egress path folds over.

use std::collections::{BTreeMap, BTreeSet};

#[path = "weld_support/cloak_population.rs"]
mod cloak_population;
#[path = "weld_support/item_resolve.rs"]
mod item_resolve;

use cloak_population::{CLOAK_DIR, CLOAK_ROOT, EligibleItem, eligible_items, src_root};
use item_resolve::{crate_rust_sources, holds_fn, holds_named_item, holds_task_id};

// ---------------------------------------------------------------------------
// Tier 1: the derived-and-welded register.
// ---------------------------------------------------------------------------

/// What an eligible in-module item IS. The distinction is the point of putting
/// the orchestrator's own items in the population: an item classified
/// `Support` is asserted NOT to be a wire transform, so adding a transform
/// under that classification is a claim a reviewer can refuse.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Role {
    /// Mutates the outgoing wire body (or decides what the mutation is).
    Transform,
    /// Config, minting, telemetry, or the orchestrator itself: reaches the
    /// orchestrator's module but writes no transform of its own.
    Support,
}

/// One tier-1 row: an eligible item of the cloak surface, with the gate it
/// rides and, where the transform gives something up, the loss it takes.
struct TierOneRow {
    /// The item's identity within its file, exactly as the derivation renders
    /// it (`name` for a free function, `Type::method` for an associated one).
    item: &'static str,
    /// The file it lives in, relative to the crate's `src`.
    file: &'static str,
    role: Role,
    /// The predicate under which it runs, from the closed vocabulary below.
    gate: Gate,
    /// Why this row is what it claims to be, in terms a reader can check
    /// against the code.
    reason: &'static str,
    /// What the transform gives up when it fires, or `None` when it loses
    /// nothing. A `Transform` row with no loss is a legitimate shape (a rename
    /// preserves everything through the reverse map); the field exists so a
    /// loss cannot be silently absent.
    known_loss: Option<&'static str>,
}

const TIER_ONE: &[TierOneRow] = &[
    TierOneRow {
        item: "strip_billing_block",
        file: "anthropic_api/cloak/billing.rs",
        role: Role::Transform,
        gate: Gate::CloakPathAlways,
        reason: "removes the client's billing/attribution system block on every cloaked request, \
                 genuine-CC included, so the client fingerprint never reaches the subscription \
                 classifier",
        known_loss: Some(
            "the client's billing/attribution block leaves the request; deliberate, and the same \
             withhold the always-on normalize path performs for non-cloak hosts",
        ),
    },
    TierOneRow {
        item: "relocate_client_system",
        file: "anthropic_api/cloak/identity.rs",
        role: Role::Transform,
        gate: Gate::CloakPathNonCc,
        reason: "reduces `system` to the identity line and moves the client's real system content \
                 into the first user message as a reminder block, so client behavior survives \
                 without the client fingerprint reaching the classifier",
        known_loss: Some(
            "three counted classes: the whole client prompt when no user message can carry it, \
             more than one client cache breakpoint collapsing to the last, and a system block \
             carrying no string text",
        ),
    },
    TierOneRow {
        item: "mint_metadata_user_id",
        file: "anthropic_api/cloak/identity.rs",
        role: Role::Transform,
        gate: Gate::CloakPathNonCc,
        reason: "writes a corpus-shaped `metadata.user_id` built from the provider's minted \
                 device and account ids, which a non-CC client supplies none of",
        known_loss: Some(
            "a caller-supplied `metadata.user_id` is replaced rather than merged, so a client \
             using that field for its own correlation loses it upstream",
        ),
    },
    TierOneRow {
        item: "normalize_tool_names_to_mcp",
        file: "anthropic_api/cloak/tool_rename.rs",
        role: Role::Transform,
        gate: Gate::CloakPathAlways,
        reason: "prefixes every non-`mcp__` custom tool name so the request is not read as \
                 first-party tool use; the returned reverse map restores the client's names on \
                 the response",
        known_loss: None,
    },
    TierOneRow {
        item: "apply_tool_rename",
        file: "anthropic_api/cloak/tool_rename.rs",
        role: Role::Transform,
        gate: Gate::CloakPathOperatorRenames,
        reason: "applies the operator's configured renames over the same tool-name paths AFTER \
                 normalization, recording into the same reverse map, so the `from` key is the \
                 post-normalization wire name",
        known_loss: Some(
            "a rename whose target collides with an existing tool name is skipped with a WARN \
             rather than applied, so the operator's configured rename silently does not happen \
             for that name",
        ),
    },
    TierOneRow {
        item: "obfuscate_sensitive_words",
        file: "anthropic_api/cloak/obfuscate.rs",
        role: Role::Transform,
        gate: Gate::CloakPathSensitiveWords,
        reason: "breaks the contiguity of operator-designated terms in system and message text \
                 with a zero-width space, so upstream keyword scanning cannot match them",
        known_loss: Some(
            "privacy hardening only, never confidentiality: the characters still travel \
             upstream, and a term the folding does not match is left contiguous",
        ),
    },
    TierOneRow {
        item: "sort_custom_tools_by_name",
        file: "anthropic_api/cloak/tool_sort.rs",
        role: Role::Transform,
        gate: Gate::CloakPathNonCcNormalizeTools,
        reason: "stable-sorts `tools[]` by the FINAL wire name so a client that shuffles tool \
                 order presents a stable cache prefix; runs last for idempotence over the \
                 post-normalization names",
        known_loss: Some(
            "all-or-nothing: any opaque, missing, or duplicate tool name stands the whole sort \
             down, giving up cache-prefix stability while every tool still rides upstream \
             verbatim",
        ),
    },
    TierOneRow {
        item: "cloak_oauth_egress",
        file: CLOAK_ROOT,
        role: Role::Support,
        gate: Gate::CloakPathAlways,
        reason: "the orchestrator itself: calls the seven transforms in their load-bearing order \
                 and flushes the per-request policy tally once, writing no wire mutation of its \
                 own",
        known_loss: None,
    },
    TierOneRow {
        item: "ClaudeCodeIdentity::mint",
        file: CLOAK_ROOT,
        role: Role::Support,
        gate: Gate::ProviderConstruction,
        reason: "mints the per-provider session, device, and account ids once at construction; \
                 touches no request body",
        known_loss: None,
    },
    TierOneRow {
        item: "CloakPolicyTally::absorb_relocation",
        file: CLOAK_ROOT,
        role: Role::Support,
        gate: Gate::CloakPathNonCc,
        reason: "folds the relocation's structural outcome into the per-request tally; telemetry \
                 bookkeeping, no body access",
        known_loss: None,
    },
    TierOneRow {
        item: "CloakPolicyTally::absorb_tool_sort",
        file: CLOAK_ROOT,
        role: Role::Support,
        gate: Gate::CloakPathNonCcNormalizeTools,
        reason: "folds the tool sort's stand-down flag into the per-request tally; telemetry \
                 bookkeeping, no body access",
        known_loss: None,
    },
    TierOneRow {
        item: "CloakPolicyTally::flush",
        file: CLOAK_ROOT,
        role: Role::Support,
        gate: Gate::CloakPathAlways,
        reason: "the single per-request flush point for the cloak's four policy-action classes, \
                 which is what keeps each key at most one record per request",
        known_loss: None,
    },
    TierOneRow {
        item: "CloakConfig::default",
        file: CLOAK_ROOT,
        role: Role::Support,
        gate: Gate::ProviderConstruction,
        reason: "the empty-default operator configuration surface (mode Auto, no renames, no \
                 sensitive words); a config constructor, not a transform",
        known_loss: None,
    },
    TierOneRow {
        item: "CloakConfig::fmt",
        file: CLOAK_ROOT,
        role: Role::Support,
        gate: Gate::ProviderConstruction,
        reason: "the hand-rolled Debug that prints mode and COUNTS only, so operator-configured \
                 renames and sensitive words cannot reach a log through a derived Debug",
        known_loss: None,
    },
    TierOneRow {
        item: "default_true_bool",
        file: CLOAK_ROOT,
        role: Role::Support,
        gate: Gate::ProviderConstruction,
        reason: "the serde field default behind the serde-skipped tool-canonicalization switch; \
                 a deserialize default, not a transform",
        known_loss: None,
    },
];

// ---------------------------------------------------------------------------
// Tier 2: the claimed-and-pinned register, with no derived side.
// ---------------------------------------------------------------------------

/// The CLOSED gate vocabulary both registers draw from. Each variant spells the
/// predicate the code actually evaluates, including the asymmetries -- an
/// [`Gate::OauthBearerOnly`] transform is NOT the same population as an
/// [`Gate::OauthBearerAnthropicHost`] one, and normalizing the two to a tidy
/// "oauth lane" name would erase the very difference a reviewer needs to see.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
enum Gate {
    /// Runs on every cloaked request: past the forwarded-leg, auth-kind, host,
    /// `CloakMode::Never`, and identity gates, on both classification arms.
    CloakPathAlways,
    /// The cloaked path AND the non-CC classification arm.
    CloakPathNonCc,
    /// The cloaked path AND the non-CC arm AND the operator's tool-canonicalization
    /// switch left on.
    CloakPathNonCcNormalizeTools,
    /// The cloaked path, with a body effect only when the operator configured
    /// at least one tool rename.
    CloakPathOperatorRenames,
    /// The cloaked path, with a body effect only when the operator configured
    /// at least one sensitive word.
    CloakPathSensitiveWords,
    /// Provider construction / config deserialization, not a per-request path.
    ProviderConstruction,
    /// The lane predicate: OauthBearer auth kind AND exactly the
    /// `api.anthropic.com` host AND not the forwarded leg. Independent of the
    /// classification and of `CloakMode`.
    ///
    /// The two dispatch sites that spell those three terms INLINE rather than
    /// calling the lane helper ride this same variant: the predicate is what a
    /// gate identifies, and two extensionally identical predicates given two
    /// names would read as two different populations. Where a row's gate is
    /// evaluated is a fact about that row, so it lives in the row's reason.
    CloakLane,
    /// The lane predicate AND the non-CC classification arm.
    CloakLaneNonCc,
    /// The lane predicate AND the assembled body carrying the field the beta
    /// gates.
    CloakLaneBodyCarriesEffort,
    /// OauthBearer auth kind ALONE -- no host check, no forwarded-leg check.
    /// Deliberately spelled apart from its siblings: this asymmetry is the
    /// register's finding, not its tidy summary.
    OauthBearerOnly,
    /// OauthBearer auth kind AND exactly the `api.anthropic.com` host, with no
    /// forwarded-leg term.
    OauthBearerAnthropicHost,
    /// The forwarded-system-turn policy: this lane targets the Anthropic wire
    /// role AND a canonical system survived the billing filter, so the
    /// `role: "system"` turns ride in place rather than being lift-consumed.
    /// Not always-on -- with no canonical system the lift owns those turns and
    /// the screening pass never runs.
    ForwardedSystemTurnPolicy,
    /// No gate: runs on every request through the surface, cloak lane or not.
    AlwaysOn,
}

impl Gate {
    /// The vocabulary itself, content-pinned. Every variant here must be used
    /// by a row, and every row's gate must be here -- both directions are
    /// asserted, so an unused variant is a gate nothing rides and a new
    /// variant cannot be introduced without a row to justify it.
    const ALL: &'static [Self] = &[
        Self::CloakPathAlways,
        Self::CloakPathNonCc,
        Self::CloakPathNonCcNormalizeTools,
        Self::CloakPathOperatorRenames,
        Self::CloakPathSensitiveWords,
        Self::ProviderConstruction,
        Self::CloakLane,
        Self::CloakLaneNonCc,
        Self::CloakLaneBodyCarriesEffort,
        Self::OauthBearerOnly,
        Self::OauthBearerAnthropicHost,
        Self::ForwardedSystemTurnPolicy,
        Self::AlwaysOn,
    ];
}

/// The number of tier-2 rows, asserted exactly. This does not prove the
/// register is complete -- tier 2 has no derived side -- but it makes deleting
/// a reviewed row a named red build rather than a silent shrink.
const TIER_TWO_ROWS: usize = 12;

/// The number of DISTINCT gates the tier-2 rows ride, asserted exactly rather
/// than as a floor. A floor is satisfied by collapsing two asymmetric
/// predicates into one shared name, which is the specific erasure recording a
/// per-row gate exists to prevent -- and it is satisfied by adding a variant
/// nothing needed. Re-derive this when a row moves; do not widen it.
const TIER_TWO_DISTINCT_GATES: usize = 7;

/// The number of crates the tier-2 rows span, asserted exactly. Two: this
/// providers crate and the shared core identity module. `routectl-auth` carries
/// the OAuth provider definitions and no lane transform, so it is not one.
const TIER_TWO_CRATES: usize = 2;

/// One tier-2 row. NAMED fields rather than a positional tuple: seven
/// assertions below read these, and a positional swap of `reason` and `test`
/// would still typecheck while pointing every pin at prose.
struct TierTwoRow {
    /// The transform's operator-facing name, unique per file.
    transform: &'static str,
    /// The file it lives in, relative to its crate's `src`.
    file: &'static str,
    /// A NAMED function or const in `file` that the claim resolves against.
    /// Never a line number and never prose: both rot, and neither can be
    /// resolved by a test.
    anchor: &'static str,
    /// Which crate's `src` the file is relative to.
    crate_root: CrateRoot,
    gate: Gate,
    /// Why this is a credential-lane transform, in terms a reader can check.
    reason: &'static str,
    /// The test that pins this row's behavior. Resolved through the same
    /// bounded matcher the counter weld's register uses.
    test: &'static str,
    /// What the transform gives up, or `None` when it gives up nothing.
    known_loss: Option<&'static str>,
}

/// The crate a tier-2 row's file is relative to. Tier 2 spanning more than one
/// crate is half of why these transforms are easy to miss.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum CrateRoot {
    Providers,
    Core,
}

/// The sibling crate whose identity module holds two of the tier-2 anchors,
/// named rather than spelled inline so a rename of the crate directory fails at
/// one place with a diagnostic instead of at every row that reaches into it.
const CORE_CRATE_DIR: &str = "routectl-core";

impl CrateRoot {
    /// The crate's `src` directory, resolved from THIS crate's manifest dir and
    /// checked to exist. Self-diagnosing on purpose: a sibling path that does
    /// not resolve reports the path it tried, rather than surfacing later as
    /// "the anchor file is unreadable" and sending the reader to the row.
    fn src(self) -> Result<std::path::PathBuf, String> {
        let path = match self {
            Self::Providers => src_root(),
            Self::Core => std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
                .parent()
                .ok_or_else(|| {
                    "this crate's manifest dir has no parent, so the workspace's crate directory \
                     cannot be located"
                        .to_string()
                })?
                .join(CORE_CRATE_DIR)
                .join("src"),
        };
        if !path.is_dir() {
            return Err(format!(
                "{} is not a readable directory, so no row anchored in it can be resolved; the \
                 sibling-crate layout this register assumes has changed",
                path.display()
            ));
        }
        Ok(path)
    }
}

const TIER_TWO: &[TierTwoRow] = &[
    TierTwoRow {
        transform: "sampling_strip",
        file: "anthropic_api/extras.rs",
        anchor: "normalize_claude_sampling",
        crate_root: CrateRoot::Providers,
        gate: Gate::CloakLane,
        reason: "the OAuth seat rejects a body carrying `temperature` or `top_p`, so both are \
                 removed as the last body mutation before egress; gated on the LANE rather than \
                 the classification, so a `mode = never` provider on this credential still ships \
                 an accepted body",
        test: "complete_and_stream_both_strip_sampling_on_the_cloak_lane",
        known_loss: Some(
            "the caller's sampling intent is discarded outright with a WARN naming the dropped \
             keys; there is no Anthropic Messages field to carry it on this seat",
        ),
    },
    TierTwoRow {
        transform: "oauth_gate_beta_union",
        file: "anthropic_api/client.rs",
        anchor: "union_oauth_gate_beta",
        crate_root: CrateRoot::Providers,
        gate: Gate::CloakLane,
        reason: "the OAuth gate flag is required for OAuth to function on this host, so it is \
                 unioned on BOTH classification arms -- unlike the floor below, one flag is not \
                 a fingerprint widening",
        test: "oauth_beta_present_for_both_genuine_cc_and_non_cc",
        known_loss: None,
    },
    TierTwoRow {
        transform: "claude_code_beta_floor",
        file: "anthropic_api/client.rs",
        anchor: "union_claude_code_beta_floor",
        crate_root: CrateRoot::Providers,
        gate: Gate::CloakLaneNonCc,
        reason: "widens a cloaked client's beta set to the pinned Claude Code floor, bypassing \
                 the client allowlist because these are operator-equivalent pins; withheld from \
                 the genuine-CC arm because force-widening a real client's set with flags it \
                 never asked for makes the upstream reject the request",
        test: "non_cc_request_gets_full_floor",
        known_loss: None,
    },
    TierTwoRow {
        transform: "beta_floor_flag_list",
        file: "identity/anthropic.rs",
        anchor: "default_claude_code_anthropic_betas",
        crate_root: CrateRoot::Core,
        gate: Gate::CloakLaneNonCc,
        reason: "the floor's flag list itself, pinned in the shared identity module rather than \
                 at the composition site, so the wire fingerprint is one literal set rather than \
                 a per-provider list",
        test: "beta_floor_all_pinned_present_on_oauth_anthropic_host",
        known_loss: None,
    },
    TierTwoRow {
        transform: "effort_beta_union",
        file: "anthropic_api/extras.rs",
        anchor: "union_effort_beta",
        crate_root: CrateRoot::Providers,
        gate: Gate::CloakLaneBodyCarriesEffort,
        reason: "the adaptive-thinking effort directive is composed only for routectl's own seat, \
                 so the beta it requires is unioned on that lane alone; one-way, so a \
                 caller-supplied effort beta with no field is left untouched",
        test: "adaptive_effort_body_gains_the_effort_beta_exactly_once",
        known_loss: None,
    },
    TierTwoRow {
        transform: "billing_checksum_resign",
        file: "claude_signing.rs",
        anchor: "resign_cch_in_place",
        crate_root: CrateRoot::Providers,
        gate: Gate::CloakLane,
        reason: "routectl mutates the body after the client computed its billing-header checksum, \
                 so the checksum is recomputed over the exact transmitted bytes; skipped on the \
                 forwarded leg, where the client's own checksum must reach the upstream verbatim. \
                 The two dispatch sites spell the lane's three terms INLINE rather than calling \
                 the lane helper, so a change to the helper does not reach them",
        test: "resign_gate_false_on_forwarded_leg_true_in_own_mode",
        known_loss: None,
    },
    TierTwoRow {
        transform: "stainless_identity_headers",
        file: "identity/anthropic.rs",
        anchor: "default_claude_code_identity_headers",
        crate_root: CrateRoot::Core,
        gate: Gate::OauthBearerOnly,
        reason: "stamps the full minted SDK client fingerprint on the auth kind ALONE, with no \
                 host term -- so an oauth-bearer provider pointed at a third-party host receives \
                 it too, unlike the session stamp beside it, which does check the host",
        test: "oauth_bearer_emits_stainless_defaults_with_empty_extras",
        known_loss: None,
    },
    TierTwoRow {
        transform: "claude_code_session_identity",
        file: "anthropic_api/client.rs",
        anchor: "stamp_claude_code_session_identity",
        crate_root: CrateRoot::Providers,
        gate: Gate::OauthBearerAnthropicHost,
        reason: "stamps a stable minted session id and a fresh per-request client-request id, \
                 host-checked so a non-Anthropic base never receives the session identity; on \
                 the forwarded leg the client's own captured pair is inserted afterwards and \
                 replaces both",
        test: "oauth_anthropic_base_stamps_stable_session_and_fresh_request_id",
        known_loss: None,
    },
    TierTwoRow {
        transform: "canonical_billing_attribution_strip",
        file: "system_filter.rs",
        anchor: "strip_billing_attribution",
        crate_root: CrateRoot::Providers,
        gate: Gate::AlwaysOn,
        reason: "the shared fingerprint-withhold predicate, called from the ALWAYS-RUN normalize \
                 path of this lane -- so an anthropic-api provider pointed at a third-party host, \
                 where the cloak never fires, still does not leak the client's billing block. The \
                 helper is lane-agnostic and three other lanes call it for the same reason; this \
                 row claims the anthropic-api call site, not exclusive ownership of the helper",
        test: "the_canonical_system_billing_strip_counts_one_policy_action",
        known_loss: Some(
            "the client's billing/attribution block leaves the request on every anthropic-api \
             egress, cloak lane or not; counted once per request as a policy action",
        ),
    },
    TierTwoRow {
        transform: "legacy_lift_billing_strip",
        file: "anthropic_api/system.rs",
        anchor: "lift_legacy_system_stripped",
        crate_root: CrateRoot::Providers,
        gate: Gate::AlwaysOn,
        reason: "the SECOND carrier of the same billing content: with no canonical system the \
                 `role: \"system\"` turns are lifted and joined into the wire system field, so the \
                 lift filters each message's text through the same predicate. Without it the \
                 canonical-path strip has a bypass any client can take by sending its system \
                 prompt as a message instead of as `system`",
        test: "the_legacy_lift_billing_strip_counts_one_policy_action",
        known_loss: Some(
            "the client's billing/attribution text leaves the request on this path too; the same \
             class and the same one-record-per-request tally the canonical strip records into, \
             because one request is one withhold however many carriers it used",
        ),
    },
    TierTwoRow {
        transform: "forwarded_system_turn_screen",
        file: "anthropic_api/messages.rs",
        anchor: "screen_forwarded_system_content",
        crate_root: CrateRoot::Providers,
        gate: Gate::ForwardedSystemTurnPolicy,
        reason: "a mid-conversation system turn forwarded in place is the THIRD carrier of the same \
                 billing content, so every text-bearing block in it runs through the shared \
                 predicate. Reached only under the forward policy -- this lane targets the \
                 Anthropic wire role AND a canonical system survived the filter -- because with no \
                 canonical system the lift consumes those turns and this pass never runs",
        test: "the_forwarded_system_turn_billing_strip_counts_one_policy_action",
        known_loss: Some(
            "blocks matching the predicate are dropped, and a turn whose every block matched is \
             skipped wholesale; counted per dropped block into the same policy class",
        ),
    },
    TierTwoRow {
        transform: "claude_code_user_agent",
        file: "anthropic_api/client.rs",
        anchor: "resolve_user_agent",
        crate_root: CrateRoot::Providers,
        gate: Gate::OauthBearerOnly,
        reason: "the client-level User-Agent is part of the minted fingerprint, not transport \
                 detail: with no operator override the OauthBearer surface presents the Claude \
                 Code CLI UA so a zero-config provider is not distinguishable by its UA alone. \
                 Gated on the auth kind ALONE, like the Stainless header set it travels with, so \
                 the same no-host-check reach applies",
        test: "oauth_bearer_user_agent_defaults_to_claude_cli",
        known_loss: Some(
            "the minted version string is a pinned literal, so it drifts behind the real client as \
             that client updates; the drift is invisible on this row and is what the corpus-derived \
             version comparison exists to surface",
        ),
    },
];

// ---------------------------------------------------------------------------
// Tier 1: the weld itself.
// ---------------------------------------------------------------------------

/// Occurrence counts of the tier-1 register, keyed on `(item, file)`. Counted
/// rather than collected so a row written twice is visible; a set would absorb
/// it and still look complete.
fn registered_counts() -> BTreeMap<(String, String), usize> {
    let mut counts: BTreeMap<(String, String), usize> = BTreeMap::new();
    for row in TIER_ONE {
        *counts
            .entry((row.item.to_string(), row.file.to_string()))
            .or_default() += 1;
    }
    counts
}

fn derived_counts(items: &[EligibleItem]) -> BTreeMap<(String, String), usize> {
    let mut counts: BTreeMap<(String, String), usize> = BTreeMap::new();
    for item in items {
        *counts
            .entry((item.item.clone(), item.file.clone()))
            .or_default() += 1;
    }
    counts
}

/// The comparison, with BOTH sides injected so a control can drive either leg
/// without writing into the source tree.
fn weld(
    derived: &BTreeMap<(String, String), usize>,
    registered: &BTreeMap<(String, String), usize>,
) -> Result<(), String> {
    if derived == registered {
        return Ok(());
    }
    let unregistered: Vec<&(String, String)> = derived
        .keys()
        .filter(|key| !registered.contains_key(*key))
        .collect();
    let stale: Vec<&(String, String)> = registered
        .keys()
        .filter(|key| !derived.contains_key(*key))
        .collect();
    // The two duplication sides are reported APART, because they are different
    // defects with different fixes and one message naming both sends the reader
    // to the wrong file. A duplicated REGISTERED key is one item enumerated
    // twice, so a reader has two reasons and no way to tell which is current. A
    // duplicated DERIVED key means the derivation produced one identity twice,
    // which is a derivation defect -- the identity renderer lost a
    // distinguishing part.
    let duplicated_registered: Vec<&(String, String)> = registered
        .iter()
        .filter(|(_, count)| **count > 1)
        .map(|(key, _)| key)
        .collect();
    let duplicated_derived: Vec<&(String, String)> = derived
        .iter()
        .filter(|(_, count)| **count > 1)
        .map(|(key, _)| key)
        .collect();
    Err(format!(
        "the cloak surface does not hold exactly the enumerated items. Eligible but unenumerated \
         (add each to TIER_ONE with its role, gate, and reason): {unregistered:?}. Enumerated but \
         absent from the surface: {stale:?}. Enumerated twice (one item, two rows -- delete one): \
         {duplicated_registered:?}. Derived twice (the derivation rendered one identity for two \
         items -- fix the renderer, not the register): {duplicated_derived:?}."
    ))
}

fn real_derived() -> BTreeMap<(String, String), usize> {
    let population = expect(cloak_population::read_population());
    derived_counts(&expect(eligible_items(&population)))
}

fn expect<T>(parsed: Result<T, String>) -> T {
    parsed.unwrap_or_else(|why| panic!("the cloak baseline cannot be evaluated: {why}"))
}

#[test]
fn the_cloak_surface_holds_exactly_the_enumerated_items() {
    // THE tier-1 weld. A function added to `cloak.rs` or to a flat file under
    // `cloak/`, with any visibility reaching the orchestrator, lands on no row
    // and fails here. That is the one shape the compiler cannot see: added AND
    // wired is neither a broken reference nor dead code.
    if let Err(why) = weld(&real_derived(), &registered_counts()) {
        panic!("{why}");
    }
}

#[test]
fn the_derived_population_covers_the_orchestrator_and_every_leaf_file() {
    // Non-vacuity on the DERIVED side, content-pinned rather than size-pinned.
    // A walk that stopped reading the orchestrator would still satisfy the
    // equality above against a register trimmed to match it -- and the
    // orchestrator is exactly where an inline transform would be added.
    let population = expect(cloak_population::read_population());
    let files: BTreeSet<&str> = population.iter().map(|(file, _)| file.as_str()).collect();
    assert!(
        files.contains(CLOAK_ROOT),
        "the orchestrator must be in the population; without it an inline transform beside it \
         evades the weld: {files:?}"
    );
    for leaf in [
        "billing.rs",
        "identity.rs",
        "obfuscate.rs",
        "tool_rename.rs",
        "tool_sort.rs",
    ] {
        let expected = format!("{CLOAK_DIR}/{leaf}");
        assert!(
            files.contains(expected.as_str()),
            "{expected} must be in the population; its absence means the walk is reading the \
             wrong directory"
        );
    }
}

#[test]
fn neither_side_of_the_tier_one_weld_is_empty() {
    // Both sides emptying at once is what a broken parse looks like, and an
    // empty-against-empty equality is green while asserting nothing.
    assert!(
        !TIER_ONE.is_empty(),
        "the tier-1 register is empty; the weld would compare nothing"
    );
    let derived = real_derived();
    assert!(
        !derived.is_empty(),
        "the derivation recovered no eligible item from a surface that demonstrably holds them"
    );
}

#[test]
fn the_enumeration_holds_both_transforms_and_classified_support_items() {
    // The classification is the second half of tier 1's value. A register of
    // transforms alone could not include the orchestrator's own file, and a
    // population without that file is one an inline transform escapes.
    let transforms = TIER_ONE
        .iter()
        .filter(|r| r.role == Role::Transform)
        .count();
    let support = TIER_ONE.iter().filter(|r| r.role == Role::Support).count();
    assert!(
        transforms > 0 && support > 0,
        "the enumeration needs both roles populated; got {transforms} transform and {support} \
         support rows"
    );
    // Every orchestrator-file row is support: a TRANSFORM claimed there is a
    // wire mutation written inline beside the orchestrator rather than in a
    // leaf module, which is a design change to argue for, not to slip in.
    for row in TIER_ONE.iter().filter(|r| r.file == CLOAK_ROOT) {
        assert_eq!(
            row.role,
            Role::Support,
            "{} sits in the orchestrator file and is classified as a transform; the transforms \
             live in leaf modules, so this is either misclassified or a design change",
            row.item
        );
    }
}

#[test]
fn every_tier_one_row_carries_a_gate_and_a_checkable_reason() {
    for row in TIER_ONE {
        assert!(
            Gate::ALL.contains(&row.gate),
            "{} rides a gate outside the closed vocabulary",
            row.item
        );
        assert!(
            row.reason.split_whitespace().count() >= 8,
            "{} carries a reason too short to check: {:?}",
            row.item,
            row.reason
        );
        assert!(
            !holds_task_id(row.reason),
            "{} carries a planning id in its reason; state something a reader of this repo can \
             check",
            row.item
        );
        if let Some(loss) = row.known_loss {
            assert!(
                loss.split_whitespace().count() >= 8,
                "{}'s known loss is too short to state one: {loss:?}",
                row.item
            );
            assert!(
                !holds_task_id(loss),
                "{}'s known loss carries a planning id",
                row.item
            );
        }
    }
}

#[test]
fn the_known_real_transforms_are_all_enumerated_as_transforms() {
    // Non-vacuity aimed at the REAL tree rather than at the register's shape.
    // A register whose rows were all reclassified to support would satisfy every
    // structural assertion above while claiming the cloak performs no transform.
    for (item, file) in [
        ("strip_billing_block", "anthropic_api/cloak/billing.rs"),
        ("relocate_client_system", "anthropic_api/cloak/identity.rs"),
        (
            "obfuscate_sensitive_words",
            "anthropic_api/cloak/obfuscate.rs",
        ),
        (
            "sort_custom_tools_by_name",
            "anthropic_api/cloak/tool_sort.rs",
        ),
    ] {
        let row = TIER_ONE
            .iter()
            .find(|r| r.item == item && r.file == file)
            .unwrap_or_else(|| panic!("{item} must be enumerated; it is a live wire transform"));
        assert_eq!(
            row.role,
            Role::Transform,
            "{item} mutates the outgoing body and must be enumerated as a transform"
        );
        assert!(
            real_derived().contains_key(&(item.to_string(), file.to_string())),
            "{item} must be derivable from {file}; if it moved, the register moves with it"
        );
    }
}

// ---------------------------------------------------------------------------
// Tier 1 controls. Each drives the derivation or the weld with INJECTED source
// it must refuse, so a derivation that silently stopped classifying is visible.
// ---------------------------------------------------------------------------

/// A one-file injected population, in the shape a leaf transform file takes.
fn injected(source: &str) -> Vec<(String, String)> {
    vec![(
        format!("{CLOAK_DIR}/injected.rs"),
        source.trim_start().to_string(),
    )]
}

fn injected_items(source: &str) -> Vec<String> {
    expect(eligible_items(&injected(source)))
        .into_iter()
        .map(|item| item.item)
        .collect()
}

fn injected_error(source: &str) -> String {
    eligible_items(&injected(source)).expect_err("this shape must be refused rather than read")
}

#[test]
fn every_visibility_that_reaches_the_orchestrator_is_eligible_whatever_its_spelling() {
    // Eligibility is a question about module depth, not about the `pub(super)`
    // spelling the seven live transforms happen to share. A weld keyed on that
    // spelling passes a `pub(crate) fn` added to a leaf file and wired into the
    // orchestrator, which is the same defect wearing a different qualifier.
    let items = injected_items(
        "
pub fn wide() {}
pub(crate) fn crate_wide() {}
pub(super) fn to_parent() {}
pub(in crate::anthropic_api) fn to_grandparent() {}
pub(in crate::anthropic_api::cloak) fn to_cloak_by_path() {}
",
    );
    assert_eq!(
        items,
        vec![
            "crate_wide",
            "to_cloak_by_path",
            "to_grandparent",
            "to_parent",
            "wide",
        ],
        "every visibility whose scope contains the orchestrator's module is eligible"
    );
}

#[test]
fn the_fn_flavor_does_not_change_eligibility() {
    // async / const / unsafe are orthogonal to visibility, and a scan keyed on
    // the token order `pub(super) fn` misses all three.
    let items = injected_items(
        "
pub(super) async fn from_async() {}
pub(super) const fn from_const() -> u8 { 0 }
pub(super) unsafe fn from_unsafe() {}
pub(super) extern \"C\" fn from_extern() {}
",
    );
    assert_eq!(
        items,
        vec!["from_async", "from_const", "from_extern", "from_unsafe"],
        "a transform's fn flavor cannot move it out of the population"
    );
}

#[test]
fn an_associated_function_is_eligible_and_carries_its_type_in_its_identity() {
    // The live surface already holds four of these. Identity includes the type
    // because two impls can carry the same method name, and collapsing them to
    // the bare name would make one row cover both.
    let items = injected_items(
        "
struct Alpha;
struct Beta;
impl Alpha {
    pub(super) fn apply() {}
    fn helper() {}
}
impl Beta {
    pub(crate) fn apply() {}
}
",
    );
    assert_eq!(
        items,
        vec!["Alpha::apply", "Beta::apply"],
        "an associated fn is eligible on its own visibility, and its type is part of its identity"
    );
}

#[test]
fn a_file_private_helper_is_excluded_while_its_visible_sibling_is_kept() {
    // The paired positive control the exclusion owes: an exclusion rule that
    // dropped everything would satisfy a negative-only assertion.
    let items = injected_items(
        "
pub(super) fn visible() {}
fn helper() {}
",
    );
    assert_eq!(
        items,
        vec!["visible"],
        "a leaf file's private helper cannot be called from the orchestrator, so it is not a \
         transform; its visible sibling must still be counted"
    );
}

#[test]
fn an_inline_module_pub_super_is_excluded_while_a_wider_sibling_is_kept() {
    // The exact case a flat declaration scan cannot get right, and the reason
    // this weld parses. Both items are spelled with a restricted visibility
    // inside the same inline module; only one of them reaches the orchestrator.
    let items = injected_items(
        "
mod inner {
    pub(super) fn only_reaches_the_leaf() {}
    pub(crate) fn reaches_the_orchestrator() {}
}
",
    );
    assert_eq!(
        items,
        vec!["inner::reaches_the_orchestrator"],
        "an inline module's `pub(super)` stops at the leaf file; the `pub(crate)` beside it does \
         not"
    );
}

#[test]
fn an_inline_cfg_test_module_is_excluded_and_production_items_below_it_are_kept() {
    // Excluded by the PARSED attribute, not by cutting the file at the first
    // `#[cfg(test)]`: every leaf file in the real surface keeps its tests in an
    // inline module, and three of them have production items after it in source
    // order. A truncating scan silently drops those.
    let items = injected_items(
        "
pub(super) fn before_tests() {}
#[cfg(test)]
mod tests {
    pub(crate) fn a_test_helper() {}
}
pub(super) fn after_tests() {}
",
    );
    assert_eq!(
        items,
        vec!["after_tests", "before_tests"],
        "the test module's contents are out of the population and the production item BELOW it is \
         still in"
    );
}

#[test]
fn a_non_test_cfg_item_stays_in_the_population() {
    // A `cfg` is not a test marker. A feature-gated or platform-gated transform
    // is a live wire transform on the configuration that enables it, so it
    // stays in the union population.
    let items = injected_items(
        "
#[cfg(feature = \"anthropic-api\")]
pub(super) fn feature_gated() {}
#[cfg(unix)]
pub(super) fn platform_gated() {}
#[cfg(all(feature = \"anthropic-api\", not(windows)))]
pub(super) fn compound_gated() {}
",
    );
    assert_eq!(
        items,
        vec!["compound_gated", "feature_gated", "platform_gated"],
        "only a `test` cfg leaves the population"
    );
}

#[test]
fn a_function_named_only_in_a_comment_or_a_string_is_not_in_the_population() {
    // A parse cannot see a ghost, which is precisely why the derivation is a
    // parse. This control exists so a future rewrite back to a text scan --
    // where both of these DO match -- fails here.
    let items = injected_items(
        "
// pub(super) fn commented_ghost() {}
/* pub(super) fn block_comment_ghost() {}  */
pub(super) fn real() {
    let _ = \"pub(super) fn string_ghost() {}\";
}
",
    );
    assert_eq!(
        items,
        vec!["real"],
        "a name in a comment or a string literal defines nothing"
    );
}

#[test]
fn an_added_eligible_function_reds_the_weld() {
    // The residual job of tier 1, demonstrated: a new eligible function on the
    // surface that joined no register row. Driven over the REAL register so the
    // failure is the one a contributor would hit.
    let mut population = expect(cloak_population::read_population());
    population.push((
        format!("{CLOAK_DIR}/billing.rs"),
        "pub(super) fn strip_something_else(body: &mut u8) { *body = 0; }\n".to_string(),
    ));
    let derived = derived_counts(&expect(eligible_items(&population)));
    let why = weld(&derived, &registered_counts())
        .expect_err("an unenumerated eligible function must not pass the weld");
    assert!(
        why.contains("strip_something_else") && why.contains("unenumerated"),
        "unexpected reason: {why}"
    );
}

#[test]
fn an_added_eligible_function_reds_the_weld_whatever_its_visibility() {
    // The same demonstration across the spellings, because the acceptance the
    // weld owes is "any visibility reaching the orchestrator", not "pub(super)".
    for spelling in [
        "pub",
        "pub(crate)",
        "pub(super)",
        "pub(in crate::anthropic_api)",
    ] {
        let mut population = expect(cloak_population::read_population());
        population.push((
            format!("{CLOAK_DIR}/identity.rs"),
            format!("{spelling} fn newly_wired_transform() {{}}\n"),
        ));
        let derived = derived_counts(&expect(eligible_items(&population)));
        let why = weld(&derived, &registered_counts())
            .expect_err("an addition at any reaching visibility must red the weld");
        assert!(
            why.contains("newly_wired_transform"),
            "a {spelling} addition must be named in the failure: {why}"
        );
    }
}

#[test]
fn a_removed_item_reds_the_weld() {
    // The other direction: a register row claiming an item that left the
    // surface reads as coverage that no longer exists.
    let mut registered = registered_counts();
    let derived = real_derived();
    let (gone, _) = registered
        .iter()
        .next()
        .map(|(key, count)| (key.clone(), *count))
        .expect("the register holds rows");
    registered.remove(&gone);
    let why = weld(&derived, &registered)
        .expect_err("a surface item with no register row must fail the weld");
    assert!(why.contains("unenumerated"), "unexpected reason: {why}");

    let mut registered = registered_counts();
    registered.insert(
        ("departed_transform".to_string(), CLOAK_ROOT.to_string()),
        1,
    );
    let why = weld(&derived, &registered)
        .expect_err("a register row with no surface item must fail the weld");
    assert!(
        why.contains("departed_transform") && why.contains("absent from the surface"),
        "unexpected reason: {why}"
    );
}

#[test]
fn the_two_duplication_sides_are_reported_apart() {
    // Pins the occurrence-COUNT comparison against a key-set simplification --
    // swapping the map comparison for a key-set one passes every other test here
    // while letting one item be classified under two contradictory rows.
    //
    // And pins the SPLIT diagnostic, because the two sides are different defects
    // with different fixes: a duplicated register row is one item with two
    // reasons (delete a row), while a duplicated derived key means the identity
    // renderer lost a distinguishing part (fix the renderer). One combined
    // message sends half the readers to the wrong file.
    let key = (
        "strip_billing_block".to_string(),
        "anthropic_api/cloak/billing.rs".to_string(),
    );
    let mut once: BTreeMap<(String, String), usize> = BTreeMap::new();
    once.insert(key.clone(), 1);
    let mut twice = BTreeMap::new();
    twice.insert(key.clone(), 2);

    let why = weld(&once, &twice).expect_err("an item enumerated twice must fail the weld");
    assert!(
        why.contains("Enumerated twice") && why.contains("delete one"),
        "the register-side duplication must name its own fix: {why}"
    );
    assert!(
        why.contains(
            "Derived twice (the derivation rendered one identity for two items -- fix \
                      the renderer, not the register): []"
        ),
        "the derived-side leg must report empty here, or the two sides are not distinguished: \
         {why}"
    );

    let why = weld(&twice, &once).expect_err("a derived key seen twice must fail the weld");
    assert!(
        why.contains("Derived twice") && why.contains("fix the renderer"),
        "the derived-side duplication must name its own fix: {why}"
    );
    assert!(
        why.contains("Enumerated twice (one item, two rows -- delete one): []"),
        "the register-side leg must report empty here: {why}"
    );

    // Paired control: a one-to-one comparison passes, so both failures above are
    // the duplication and not the fixture.
    weld(&once, &once).expect("a one-to-one enumeration passes");
}

#[test]
fn a_duplicate_eligible_identity_in_one_file_is_refused() {
    // Two eligible items that render to one identity would be counted once,
    // which silently halves the population. Unreachable in real Rust through
    // free functions, reachable through two inherent impls of the same type.
    let why = injected_error(
        "
struct Alpha;
impl Alpha {
    pub(super) fn apply() {}
}
impl Alpha {
    pub(crate) fn apply() {}
}
",
    );
    assert!(
        why.contains("cannot tell them apart"),
        "unexpected reason: {why}"
    );
}

#[test]
fn every_item_position_macro_invocation_is_refused() {
    // The catch-all, which is the point of this control. A macro at item position
    // can expand to function items, and this derivation reads source BEFORE
    // expansion -- so it cannot see what any of them produce, whether the macro
    // is defined here, imported from elsewhere in the crate, or a procedural
    // macro from a dependency. Enumerating the two familiar ones and skipping the
    // rest is how a population silently shrinks.
    let why = injected_error(
        "
macro_rules! makes_transforms {
    () => {};
}
",
    );
    assert!(why.contains("defines a macro"), "unexpected reason: {why}");

    // The fragment-pulling macro is spelled from its parts rather than written
    // out: the repo's fragment-format gate fails closed on any occurrence of
    // that token it cannot resolve to a real file, and this fixture's target
    // does not exist.
    let fragment_macro = format!("{}!(\"elsewhere.rs\");\n", "include");
    let why = injected_error(&fragment_macro);
    assert!(
        why.contains("source fragment at item position"),
        "unexpected reason: {why}"
    );

    // An EXTERNAL macro from elsewhere in the crate, and a PROC-MACRO-shaped
    // invocation from a dependency. Neither is `macro_rules!` nor the fragment
    // puller, so before the catch-all both rode through and whatever they expand
    // to left the population unseen.
    for invocation in [
        "crate::wire_transforms!(billing, identity);\n",
        "define_transforms! { strip_x, strip_y }\n",
        "some_dep::generate_lane_transforms!(cloak);\n",
    ] {
        let why = injected_error(invocation);
        assert!(
            why.contains("at item position") && why.contains("before expansion"),
            "an unknown item-position macro must be refused by the catch-all: {invocation:?} gave \
             {why}"
        );
    }
}

#[test]
fn a_macro_invocation_inside_an_impl_or_a_trait_is_refused() {
    // The same blindness one level down. An impl-body or trait-body macro can
    // expand to associated functions, and the walk over `block.items` sees only
    // the invocation.
    let why = injected_error(
        "
struct Alpha;
impl Alpha {
    generated_methods!();
}
",
    );
    assert!(
        why.contains("inside the impl for `Alpha`"),
        "unexpected reason: {why}"
    );

    let why = injected_error(
        "
pub(super) trait Cloaks {
    generated_methods!();
}
",
    );
    assert!(
        why.contains("inside trait `Cloaks`"),
        "unexpected reason: {why}"
    );
}

#[test]
fn a_trait_default_body_is_eligible_on_the_traits_own_visibility() {
    // A default body is a real function body that ships, and it is callable
    // wherever the trait is nameable -- so its scope is the TRAIT's visibility,
    // not the impl's and not `crate`. Before this the whole item kind was
    // skipped, so a transform written as a default body was invisible.
    let items = injected_items(
        "
pub(super) trait ReachesOrchestrator {
    fn defaulted(&self) {}
    fn signature_only(&self);
}
trait FilePrivate {
    fn also_defaulted(&self) {}
}
",
    );
    assert_eq!(
        items,
        vec!["ReachesOrchestrator::defaulted"],
        "the reaching trait's DEFAULT body is in; its signature-only sibling ships no code, and \
         the file-private trait's default body cannot be reached from the orchestrator"
    );
}

#[test]
fn a_trait_default_body_leaves_the_population_when_gated_or_unclassifiable() {
    // The test-gated default body is out, like any other test-gated item.
    let items = injected_items(
        "
pub(crate) trait Cloaks {
    #[cfg(test)]
    fn test_only(&self) {}
    fn production(&self) {}
}
",
    );
    assert_eq!(items, vec!["Cloaks::production"]);

    // And a trait member shape the derivation cannot classify is refused rather
    // than skipped, because a skipped member is one whose body left the
    // population with nothing red.
    let why = injected_error(
        "
pub(super) trait Cloaks {
    unknown_member!();
}
",
    );
    assert!(why.contains("inside trait `Cloaks`"));
}

#[test]
fn a_trait_impls_members_are_bounded_by_the_self_types_declared_visibility() {
    // Trait-impl members carry no visibility of their own, so the scope comes
    // from the declaration they hang off. Hardcoding `crate` here -- as this
    // derivation first did -- over-includes the members of a FILE-PRIVATE type's
    // trait impl, which the orchestrator cannot name and therefore cannot call.
    let items = injected_items(
        "
pub(super) struct Reachable;
struct FilePrivate;
impl Default for Reachable {
    fn default() -> Self { Self }
}
impl Default for FilePrivate {
    fn default() -> Self { Self }
}
",
    );
    assert_eq!(
        items,
        vec!["Reachable::default"],
        "the reaching type's trait-impl member is in; the file-private type's is not, because the \
         orchestrator cannot name the type to call it"
    );
}

#[test]
fn an_inherited_self_type_in_the_orchestrator_file_still_reaches_the_target() {
    // The real tree depends on this: the orchestrator's own tally type is
    // declared with inherited visibility, and inherited AT the cloak module IS
    // the target module -- so its trait-impl members are eligible. A rule that
    // required an explicit qualifier would drop them.
    let items = expect(eligible_items(&[(
        CLOAK_ROOT.to_string(),
        "
struct Tally;
impl Default for Tally {
    fn default() -> Self { Self }
}
"
        .to_string(),
    )]))
    .into_iter()
    .map(|item| item.item)
    .collect::<Vec<String>>();
    assert_eq!(items, vec!["Tally::default"]);
}

#[test]
fn a_trait_impl_for_a_type_declared_elsewhere_is_refused() {
    // The visibility bounding the members cannot be resolved without the
    // declaration, and assuming crate-wide reach is the over-inclusion this
    // refusal replaced.
    let why = injected_error(
        "
impl Default for FromAnotherFile {
    fn default() -> Self { Self }
}
",
    );
    assert!(
        why.contains("not declared in this file")
            && why.contains("Refusing rather than assuming crate-wide reach"),
        "unexpected reason: {why}"
    );
}

#[test]
fn an_unclassifiable_visibility_path_is_refused_quoting_the_spelling_as_written() {
    // A `pub(in ...)` naming a module this derivation cannot place could be
    // narrower or wider than the orchestrator, and guessing either way moves an
    // item across the population boundary silently.
    let why = injected_error("pub(in some::other::place) fn ambiguous() {}\n");
    assert!(why.contains("cannot resolve"), "unexpected reason: {why}");
    assert!(
        why.contains("`pub(in some::other::place)`"),
        "the diagnostic must quote the spelling AS WRITTEN so a reader can find it: {why}"
    );

    // The other reachable diagnostic on this path, quoted the same way. The
    // derivation used to build every message as `pub(in {segments})`, which
    // renders a bare `pub(super)` chain as a `pub(in ...)` the author never
    // typed -- so a reader searching the file for the quoted string finds
    // nothing. (Rust admits only `crate`, `self`, and `super` without `in`, and
    // all three are classifiable, so this climb message is where the invented
    // `in` would surface.)
    let why = eligible_items(&[(
        format!("{CLOAK_DIR}/injected.rs"),
        "pub(in super::super::super::super::super) fn climbs_out() {}\n".to_string(),
    )])
    .expect_err("a visibility climbing past the crate root must be refused");
    assert!(
        why.contains("climbs past the crate root")
            && why.contains("`pub(in super::super::super::super::super)`"),
        "the climb diagnostic must quote the spelling exactly once, as written: {why}"
    );

    // Paired positive control: the forms that ARE classifiable must not be
    // refused, or the refusal would red-fail correct code.
    let items = injected_items(
        "
pub(in crate::anthropic_api::cloak) fn at_target() {}
pub(in crate) fn at_root() {}
pub(self) fn at_self() {}
",
    );
    assert_eq!(items, vec!["at_root", "at_target"]);
}

#[test]
fn a_parse_error_is_refused_rather_than_read_as_an_empty_file() {
    // An empty result from a broken parse removes a whole file's items from
    // this side of the weld, which is green by having less to compare.
    let why = injected_error("pub(super) fn broken( {\n");
    assert!(
        why.contains("does not parse as Rust"),
        "unexpected reason: {why}"
    );
}

#[test]
fn a_cfg_is_test_only_iff_no_production_configuration_enables_it() {
    // The correction that matters most in this group. Classification is a
    // SATISFIABILITY question, not a token search: evaluate the predicate with
    // `test` false and every other atom unknown, and the item is test-only only
    // when the result is definitely false.
    //
    // A token search for `test` calls all four of these test-only, and the two
    // union forms below are live in a production build -- so the token search
    // silently drops real items from the population.
    let items = injected_items(
        "
#[cfg(test)]
pub(super) fn bare_test() {}
#[cfg(all(test, unix))]
pub(super) fn conjunction_with_test() {}
#[cfg(any(test, feature = \"anthropic-api\"))]
pub(super) fn union_with_a_feature() {}
#[cfg(any(test, unix))]
pub(super) fn union_with_a_platform() {}
",
    );
    assert_eq!(
        items,
        vec!["union_with_a_feature", "union_with_a_platform"],
        "the two conjunctive forms are unsatisfiable without `test` and leave the population; the \
         two UNION forms are enabled in a production configuration and must stay in it"
    );
}

#[test]
fn several_cfg_attributes_on_one_item_are_a_conjunction() {
    // Stacked `cfg`s are ANDed by the compiler, so any one of them being
    // unsatisfiable without `test` makes the item test-only. Reading only the
    // first attribute keeps a test-only item in the population.
    let items = injected_items(
        "
#[cfg(unix)]
#[cfg(test)]
pub(super) fn gated_by_the_second() {}
#[cfg(unix)]
#[cfg(feature = \"anthropic-api\")]
pub(super) fn production_on_both() {}
",
    );
    assert_eq!(items, vec!["production_on_both"]);
}

#[test]
fn a_cfg_that_negates_test_is_refused_while_a_non_test_negation_is_read() {
    // `not(test)` is a PRODUCTION item wearing a test-shaped attribute: read as
    // test-gated it silently leaves the population, read as production the
    // attribute's meaning was ignored. Neither is a call to make silently.
    for negated in [
        "#[cfg(not(test))]",
        "#[cfg(all(unix, not(test)))]",
        "#[cfg(any(not(test), feature = \"x\"))]",
    ] {
        let why = injected_error(&format!("{negated}\npub(super) fn f() {{}}\n"));
        assert!(
            why.contains("NEGATES `test`"),
            "{negated} must be refused: {why}"
        );
    }

    // The must-be-ACCEPTED half: a `not` that does NOT wrap `test` is a plain
    // platform or feature negation, and refusing every attribute containing both
    // tokens -- which the first version of this rule did -- red-fails correct
    // code. `all(test, not(windows))` is unambiguously test-only.
    let items = injected_items(
        "
#[cfg(all(test, not(windows)))]
pub(super) fn test_only_on_non_windows() {}
#[cfg(not(windows))]
pub(super) fn production_on_non_windows() {}
#[cfg(all(not(windows), feature = \"anthropic-api\"))]
pub(super) fn production_compound() {}
",
    );
    assert_eq!(
        items,
        vec!["production_compound", "production_on_non_windows"],
        "a `not` that does not wrap `test` is an ordinary negation: the test-only item leaves the \
         population and the two production items stay in it"
    );
}

#[test]
fn a_cfg_attr_that_can_inject_a_gate_or_a_path_is_refused() {
    // A `cfg_attr` expands to the attributes in its tail, so one that can add a
    // `#[path]` redirect or a `cfg` gate changes the two facts this derivation
    // depends on -- and only under a configuration it cannot evaluate. Reading it
    // under one arbitrary configuration is a guess.
    for injecting in [
        "#[cfg_attr(test, path = \"elsewhere.rs\")]",
        "#[cfg_attr(unix, cfg(test))]",
        "#[cfg_attr(feature = \"x\", cfg_attr(test, path = \"e.rs\"))]",
    ] {
        let why = injected_error(&format!("{injecting}\npub(super) fn f() {{}}\n"));
        assert!(
            why.contains("`cfg_attr` that can add"),
            "{injecting} must be refused: {why}"
        );
    }

    // Paired positive control: an ordinary `cfg_attr` that adds a lint or a
    // derive-adjacent attribute injects neither, so it must not be refused.
    let items = injected_items(
        "
#[cfg_attr(test, allow(dead_code))]
pub(super) fn linted() {}
#[cfg_attr(feature = \"anthropic-api\", inline)]
pub(super) fn inlined() {}
",
    );
    assert_eq!(items, vec!["inlined", "linted"]);
}

#[test]
fn a_production_path_redirect_is_refused_and_a_cfg_test_sidecar_is_not() {
    // A production `#[path]` means the walk reads one file while the compiler
    // reads another, so the population is a fiction.
    let why = injected_error(
        "
#[path = \"elsewhere.rs\"]
mod redirected;
",
    );
    assert!(
        why.contains("`#[path]` redirect"),
        "unexpected reason: {why}"
    );

    // The must-be-ACCEPTED half, drawn from the real tree: the orchestrator keeps
    // two test modules in sibling files exactly this way, so a refusal that did
    // not distinguish them would red-fail correct code and get loosened. This is
    // also the control on threading the classification through rather than
    // re-deriving it at the refusal, since the refusal's decision depends on it.
    let items = injected_items(
        "
pub(super) fn real() {}
#[cfg(test)]
#[path = \"injected_tests.rs\"]
mod tests;
",
    );
    assert_eq!(items, vec!["real"]);
}

#[test]
fn an_eligible_function_pointer_value_is_refused_rather_than_silently_missed() {
    // A transform held in a `const` or `static` of function-pointer type is
    // callable without being a function item, so the walk cannot see it. This
    // derivation does not follow value initializers -- a stated CEILING -- and it
    // refuses the shape rather than leaving a silent hole where a reader would
    // assume coverage.
    for declaration in [
        "pub(super) const APPLY: fn(&mut u8) = strip;\n",
        "pub(super) static APPLY: fn(&mut u8) = strip;\n",
        "pub(crate) const APPLY: &fn(&mut u8) = &strip;\n",
    ] {
        let why = injected_error(declaration);
        assert!(
            why.contains("function-pointer type") && why.contains("Give it a named `fn`"),
            "{declaration:?} must be refused: {why}"
        );
    }

    // Paired positive control: an ordinary const or static is not refused, or
    // every file in the real surface would fail (three of them carry one).
    let items = injected_items(
        "
pub(super) const PREFIX: &str = \"x-billing:\";
pub(super) static COUNT: u8 = 0;
pub(super) fn real() {}
",
    );
    assert_eq!(items, vec!["real"]);
}

#[test]
fn a_subdirectory_under_the_leaf_directory_is_refused_rather_than_skipped() {
    // The walk is flat. A subdirectory's items would leave this side of the
    // weld entirely, and fewer items to compare is green by having less to
    // check. Driven through the module-path derivation rather than by creating
    // a directory in the tree.
    let why = eligible_items(&[(
        format!("{CLOAK_DIR}/nested/deeper.rs"),
        "pub(super) fn hidden() {}\n".to_string(),
    )])
    .expect_err("a nested path must be refused");
    assert!(why.contains("does not descend"), "unexpected reason: {why}");
}

#[test]
fn a_test_sidecar_under_the_leaf_directory_is_refused_rather_than_given_a_false_module_path() {
    // A sidecar is pulled in by a `#[path]` from whichever module owns it, so
    // calling it `cloak::<stem>` assigns it a module path it does not have -- and
    // then every item in it is measured against the WRONG scope, which moves
    // items into and out of the population arbitrarily. The orchestrator already
    // keeps two sidecars this way, so the shape is live in this repo.
    for sidecar in ["cloak_tests.rs", "identity_test_support.rs"] {
        let why = eligible_items(&[(
            format!("{CLOAK_DIR}/{sidecar}"),
            "pub(super) fn helper() {}\n".to_string(),
        )])
        .expect_err("a sidecar must be refused rather than measured as a leaf module");
        assert!(
            why.contains("test sidecar"),
            "{sidecar} must be refused: {why}"
        );
    }

    // Paired positive control: an ordinary leaf name is NOT read as a sidecar,
    // or the real population would be empty.
    for real in ["billing.rs", "identity.rs", "tool_sort.rs"] {
        assert!(
            !cloak_population::is_test_sidecar(real),
            "{real} is a production leaf and must not be read as a sidecar"
        );
    }
}

#[test]
fn the_real_leaf_directory_holds_no_symlink_or_sidecar() {
    // The file-level refusals above are driven through injected paths, so this is
    // the assertion that the REAL directory satisfies them -- and it is what
    // makes `read_population` succeeding elsewhere in this binary meaningful
    // rather than incidental. A symlink or a sidecar landing there is a red
    // build here with a named reason.
    expect(cloak_population::population_files());
}

#[test]
fn a_file_added_to_or_removed_from_the_surface_reds_the_weld() {
    // File-population controls. A new leaf module contributes items no row
    // claims; a deleted one leaves rows claiming items nothing carries.
    let mut population = expect(cloak_population::read_population());
    population.push((
        format!("{CLOAK_DIR}/added_module.rs"),
        "pub(super) fn transform_from_a_new_file() {}\n".to_string(),
    ));
    let why = weld(
        &derived_counts(&expect(eligible_items(&population))),
        &registered_counts(),
    )
    .expect_err("a new file's eligible items must not pass unenumerated");
    assert!(
        why.contains("transform_from_a_new_file"),
        "unexpected reason: {why}"
    );

    let mut population = expect(cloak_population::read_population());
    population.retain(|(file, _)| file != "anthropic_api/cloak/billing.rs");
    let why = weld(
        &derived_counts(&expect(eligible_items(&population))),
        &registered_counts(),
    )
    .expect_err("a removed file must leave its rows claiming nothing");
    assert!(
        why.contains("strip_billing_block") && why.contains("absent from the surface"),
        "unexpected reason: {why}"
    );
}

// ---------------------------------------------------------------------------
// Tier 2: the register's own contract. Nothing here derives the POPULATION --
// see the module doc's ceiling -- but every CLAIM a row makes is checked.
// ---------------------------------------------------------------------------

#[test]
fn every_tier_two_anchor_resolves_to_a_named_item_in_the_file_it_names() {
    // The row names a FILE and an ANCHOR, and this is what keeps the pair
    // honest: a transform that moved, was renamed, or was inlined away leaves
    // the row pointing at nothing. An anchor is a named function or const on
    // purpose -- a line number or a prose description cannot be resolved by a
    // test, so it decays into an unchecked comment.
    for row in TIER_TWO {
        let path = expect(row.crate_root.src()).join(row.file);
        let source = expect(
            std::fs::read_to_string(&path)
                .map_err(|err| format!("{} must be readable ({err})", row.file)),
        );
        let resolved = expect(holds_named_item(&source, row.anchor));
        assert!(
            resolved,
            "the register says {} is anchored at `{}` in {}, which carries no item by that name. \
             Re-point the row, or restore the anchor.",
            row.transform, row.anchor, row.file
        );
    }
}

#[test]
fn the_tier_two_anchor_resolution_refuses_a_name_the_file_does_not_carry() {
    // Paired positive control on the resolver above: it must be able to fail,
    // and it must not accept a name that appears only in a comment or a string.
    // Without this, a resolver that returned `true` unconditionally would leave
    // every row above green.
    let source = "
// fn commented_anchor() {}
fn real_anchor() { let _ = \"string_anchor\"; }
const REAL_CONST: u8 = 0;
struct T;
impl T { fn assoc_anchor() {} }
";
    assert!(expect(holds_named_item(source, "real_anchor")));
    assert!(expect(holds_named_item(source, "REAL_CONST")));
    assert!(expect(holds_named_item(source, "assoc_anchor")));
    assert!(!expect(holds_named_item(source, "commented_anchor")));
    assert!(!expect(holds_named_item(source, "string_anchor")));
    assert!(!expect(holds_named_item(source, "real_anchor_extra")));
    // A parse failure is an error, not a `false`: reporting a broken checkout
    // as a broken register sends the reader to the wrong place.
    assert!(holds_named_item("fn broken( {", "broken").is_err());
}

#[test]
fn every_tier_two_row_names_a_pinning_test_that_exists() {
    // Without this the covering test is named only in prose, and nothing parses
    // prose: deleting the test that pins a transform would leave every weld
    // green. Resolved through the SAME bounded matcher the counter weld's
    // register uses, so the two kinds of pin cannot disagree about what
    // "resolves" means.
    let sources = expect(crate_rust_sources());
    for row in TIER_TWO {
        let hits = sources
            .iter()
            .filter(|(_, source)| holds_fn(source, row.test))
            .count();
        assert!(
            hits > 0,
            "the row for {} names test={}, which pins nothing: no `fn {}` exists in this crate. \
             Restore the test or re-point the row.",
            row.transform,
            row.test,
            row.test
        );
    }
}

#[test]
fn the_pinning_test_resolution_refuses_a_name_no_function_carries() {
    // Paired positive control on the shared resolver: a substring match would
    // find `fn <name>_extra` and report a deleted test as present.
    assert!(!holds_fn("fn planted_pin_extra() {}\n", "planted_pin"));
    assert!(holds_fn("fn planted_pin_extra() {}\n", "planted_pin_extra"));
    assert!(holds_fn("    async fn planted_pin() {}\n", "planted_pin"));
}

#[test]
fn the_shared_pinning_corpus_covers_both_src_and_tests() {
    // The SCOPE of the corpus, asserted directly rather than through a row.
    //
    // Stated plainly because a mutation cannot currently prove it: every pin
    // name in this crate today happens to resolve under `src/` (the sidecar
    // `_tests.rs` files live there), so narrowing the corpus to `src/` alone
    // reds nothing and looks safe. The moment one pinning test is written in an
    // integration binary -- which is where this crate puts every weld -- the
    // narrow corpus reports it as deleted and reds a correct register.
    //
    // So the invariant this asserts is the corpus SHAPE, which is what the two
    // consumers must agree on, and it is content-pinned in both directions
    // rather than counted.
    let sources = expect(crate_rust_sources());
    let paths: Vec<&str> = sources.iter().map(|(path, _)| path.as_str()).collect();
    for required in [
        // A production module, an inline-test-carrying sidecar under `src/`, and
        // this very binary under `tests/` -- one per place a pin can live.
        "anthropic_api/cloak.rs",
        "anthropic_api/mod_tests.rs",
        "tests/cloak_baseline_weld.rs",
    ] {
        assert!(
            paths.iter().any(|path| path.ends_with(required)),
            "the shared pinning corpus must reach {required}; without it a test living there \
             resolves against nothing and a correct register reds. Recovered {} files.",
            paths.len()
        );
    }
    // And the corpus is the same object both registers read: the counter weld
    // resolves its own `test=` names through this function, so a scope change
    // here moves both at once by construction rather than by convention.
    assert!(
        holds_fn(
            &sources
                .iter()
                .map(|(_, source)| source.as_str())
                .collect::<Vec<&str>>()
                .join("\n"),
            "the_legacy_lift_billing_strip_counts_one_policy_action"
        ),
        "a known real pinning test must resolve in the shared corpus, or the corpus is reading \
         the wrong tree"
    );
}

#[test]
fn every_tier_two_row_is_a_distinct_transform_with_its_own_test() {
    // Two rows naming one test means that test reds when either arm breaks, so
    // each row LOOKS pinned while no row is pinned individually -- the
    // per-transform signal the register exists to carry collapses to one bit.
    //
    // Rows are identified on `(transform, file)` rather than on the transform
    // alone because the same withhold legitimately appears on two files (the
    // cloak strip and the always-on normalize strip), so the name alone is not
    // the identity.
    let mut tests: Vec<&str> = TIER_TWO.iter().map(|row| row.test).collect();
    tests.sort_unstable();
    let mut distinct = tests.clone();
    distinct.dedup();
    assert_eq!(
        tests, distinct,
        "two rows name the same pinning test; each needs its own, or deleting one transform's \
         coverage reds a test another row was relying on"
    );

    let mut rows: Vec<(&str, &str)> = TIER_TWO
        .iter()
        .map(|row| (row.transform, row.file))
        .collect();
    rows.sort_unstable();
    let mut distinct_rows = rows.clone();
    distinct_rows.dedup();
    assert_eq!(
        rows, distinct_rows,
        "two rows declare the same (transform, file); one declaration per site, or a reader \
         cannot tell which reason is current"
    );
}

#[test]
fn every_tier_two_row_carries_a_checkable_reason_and_a_stated_loss_or_none() {
    // The reason IS the value of a row that has no derived side: the register
    // proves the row is real, so the reason is what a reviewer re-takes when
    // the surface changes. A blank or placeholder reason is an unexplained
    // claim wearing the shape of a decision.
    for row in TIER_TWO {
        assert!(
            row.reason.split_whitespace().count() >= 12,
            "{} carries a reason too short to be one: {:?}",
            row.transform,
            row.reason
        );
        assert!(
            !holds_task_id(row.reason),
            "{} carries a planning id; state a reason a reader of this repo can check",
            row.transform
        );
        assert!(
            !row.reason.contains(".rs:"),
            "{}'s reason carries a file:line reference, which rots on the next edit above it",
            row.transform
        );
        if let Some(loss) = row.known_loss {
            assert!(
                loss.split_whitespace().count() >= 8,
                "{}'s known loss is too short to state one: {loss:?}",
                row.transform
            );
            assert!(
                !holds_task_id(loss),
                "{}'s known loss carries a planning id",
                row.transform
            );
        }
    }
}

#[test]
fn the_gate_vocabulary_is_closed_and_every_gate_is_ridden() {
    // Both directions. A row on a gate outside the vocabulary is an
    // unclassified predicate; a vocabulary variant no row rides is a gate that
    // reads as covered while covering nothing -- and the asymmetries are the
    // whole point of spelling the predicates out, so an unused variant is
    // likely a transform that was dropped from the register.
    let vocabulary: BTreeSet<Gate> = Gate::ALL.iter().copied().collect();
    assert_eq!(
        vocabulary.len(),
        Gate::ALL.len(),
        "the pinned vocabulary lists a gate twice"
    );
    let ridden: BTreeSet<Gate> = TIER_ONE
        .iter()
        .map(|row| row.gate)
        .chain(TIER_TWO.iter().map(|row| row.gate))
        .collect();
    let unridden: Vec<&Gate> = vocabulary.difference(&ridden).collect();
    assert!(
        unridden.is_empty(),
        "these gates are in the vocabulary and no row rides them: {unridden:?}. Either a row was \
         dropped or the variant is a predicate the code no longer evaluates."
    );
    let unknown: Vec<&Gate> = ridden.difference(&vocabulary).collect();
    assert!(
        unknown.is_empty(),
        "these gates are ridden and not in the closed vocabulary: {unknown:?}"
    );
}

#[test]
fn tier_two_spans_the_derived_crate_and_gate_counts_exactly() {
    // Non-vacuity aimed at the register's REASON FOR EXISTING, and pinned
    // EXACTLY rather than as a floor in both directions.
    //
    // A floor (`>= n`) is satisfied by collapsing two asymmetric predicates into
    // one shared name as long as enough others remain, which is precisely the
    // erasure recording a per-row gate exists to prevent -- and it is also
    // satisfied by adding a variant no row needed. An exact count makes either
    // move a red build that names the number, so whoever changes the population
    // re-derives it deliberately instead of letting it drift.
    assert_eq!(
        TIER_TWO.len(),
        TIER_TWO_ROWS,
        "the register holds {} rows and the pinned count is {TIER_TWO_ROWS}. The count does not \
         prove completeness, but a reviewed row must not disappear silently.",
        TIER_TWO.len()
    );
    let crates: BTreeSet<&str> = TIER_TWO
        .iter()
        .map(|row| match row.crate_root {
            CrateRoot::Providers => "providers",
            CrateRoot::Core => "core",
        })
        .collect();
    assert_eq!(
        crates.len(),
        TIER_TWO_CRATES,
        "the register spans {crates:?}; the pinned count is {TIER_TWO_CRATES}. Re-derive the \
         constant if the population genuinely moved -- do not widen it to absorb a row that \
         landed in the wrong crate."
    );
    let gates: BTreeSet<Gate> = TIER_TWO.iter().map(|row| row.gate).collect();
    assert_eq!(
        gates.len(),
        TIER_TWO_DISTINCT_GATES,
        "the register rides {} distinct gates and the pinned count is {TIER_TWO_DISTINCT_GATES}: \
         {gates:?}. Fewer means two predicates were normalized into one shared name, which erases \
         the asymmetry the per-row gate exists to record; more means a variant was added without \
         re-deriving the count.",
        gates.len()
    );
    // The two asymmetric header gates specifically, because they are the
    // finding: one sibling checks the host and the other does not.
    assert!(
        gates.contains(&Gate::OauthBearerOnly) && gates.contains(&Gate::OauthBearerAnthropicHost),
        "the host-check asymmetry between the two identity-header sites must stay enumerated on \
         both sides: {gates:?}"
    );
    // And an always-on row, which no lane-predicate scan would ever find --
    // the reason a partial derived side was rejected rather than approximated.
    assert!(
        gates.contains(&Gate::AlwaysOn),
        "the always-on transforms must stay in the register: they are invisible to any scan of \
         the lane predicate's call sites"
    );
    // And the forward-policy gate, which is the correction that made this count
    // move: the screening pass reads as always-on and is not.
    assert!(
        gates.contains(&Gate::ForwardedSystemTurnPolicy),
        "the forwarded-turn screening pass runs only under the forward policy; classifying it \
         always-on overstates where it fires: {gates:?}"
    );
}

#[test]
fn the_tier_two_register_states_that_it_has_no_derived_side() {
    // The ceiling, asserted rather than only written, because a register with no
    // derived side is exactly the shape that gets over-read as complete. This
    // reads the binary's own module doc: if the ceiling is edited out, the
    // register stops carrying the statement that makes it honest.
    //
    // Coupling a test to prose is accepted here for one reason: the register's
    // honesty IS the prose. There is nothing else to assert -- an absent derived
    // side leaves no artifact a test could measure.
    let source = expect(
        std::fs::read_to_string(std::path::Path::new(file!()))
            .or_else(|_| {
                std::fs::read_to_string(
                    std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
                        .join("tests/cloak_baseline_weld.rs"),
                )
            })
            .map_err(|err| format!("this binary's own source must be readable ({err})")),
    );
    let doc: String = source
        .lines()
        .take_while(|line| line.starts_with("//!") || line.is_empty())
        .filter_map(|line| line.strip_prefix("//!"))
        .map(str::trim)
        .collect::<Vec<&str>>()
        .join(" ");
    for required in [
        "no honest tree-to-register derived side",
        "CANNOT prove no row is missing",
    ] {
        assert!(
            doc.contains(required),
            "the module doc must state the tier-2 ceiling verbatim; {required:?} is missing, so \
             the register would read as complete"
        );
    }
}
