//! JSON Schema rendering for the on-disk `config.toml` surface.
//!
//! [`render_schema_json`] is the single source of the committed
//! `routectl.schema.json` at the repo root. The `gen_schema` binary writes
//! that artifact; a golden test in this module pins the committed bytes to
//! this function's output so the two can never silently diverge.

use crate::config::{CURRENT_CONFIG_VERSION, Config, routectl_config_dir};

/// Root-level key carrying the config version this schema was generated
/// against. This is METADATA, not a hard constraint on the `version` field:
/// editors must keep accepting older-but-migratable configs the binary still
/// loads, so the schema never pins `version` to a single const.
const VERSION_KEY: &str = "x-routectl-config-version";

/// Root-level marker flagging the artifact as machine-generated. The golden
/// test asserts its presence so a hand edit to the committed file is caught.
const GENERATED_KEY: &str = "x-generated";
const GENERATED_MARKER: &str = "@generated by `cargo run --bin gen_schema` -- do not edit by hand";

/// Machine-independent stand-in for the user config dir in emitted schema
/// defaults. Path-typed fields (`[mitm] cert_dir`, `[usage] db_path`) default
/// to a path under [`routectl_config_dir`], which resolves `XDG_CONFIG_HOME` /
/// `HOME` at generation time -- an absolute, box-specific path that must never
/// reach the committed artifact. The runtime serde defaults are unchanged; only
/// the rendered schema's default strings are rewritten to this placeholder.
const CONFIG_DIR_PLACEHOLDER: &str = "~/.config/routectl";

/// Recursively rewrite any string value whose prefix is the resolved
/// `routectl_config_dir()` to [`CONFIG_DIR_PLACEHOLDER`], so the rendered
/// schema carries no machine-specific home path. Applies to every string in
/// the tree, which reaches both the field-level `default` on the two path
/// fields and the whole-object `default` schemars emits for the parent
/// `[usage]` block.
fn stabilize_config_dir_defaults(value: &mut serde_json::Value, config_dir: &str) {
    match value {
        serde_json::Value::String(s) => {
            if let Some(rest) = s.strip_prefix(config_dir) {
                *s = format!("{CONFIG_DIR_PLACEHOLDER}{rest}");
            }
        }
        serde_json::Value::Array(items) => {
            for item in items {
                stabilize_config_dir_defaults(item, config_dir);
            }
        }
        serde_json::Value::Object(map) => {
            for child in map.values_mut() {
                stabilize_config_dir_defaults(child, config_dir);
            }
        }
        _ => {}
    }
}

/// Renders the config JSON Schema as pretty-printed JSON with a trailing
/// newline. Deterministic: repeated calls are byte-identical.
pub fn render_schema_json() -> String {
    let schema = schemars::schema_for!(Config);
    let mut value = serde_json::to_value(&schema).expect("config schema serializes to JSON");

    let config_dir = routectl_config_dir().to_string_lossy().into_owned();
    stabilize_config_dir_defaults(&mut value, &config_dir);

    let root = value
        .as_object_mut()
        .expect("config schema root is a JSON object");
    root.insert(
        VERSION_KEY.to_string(),
        serde_json::Value::from(CURRENT_CONFIG_VERSION),
    );
    root.insert(
        GENERATED_KEY.to_string(),
        serde_json::Value::from(GENERATED_MARKER),
    );

    let mut out = serde_json::to_string_pretty(&value).expect("schema value pretty-prints");
    out.push('\n');
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The committed artifact must equal what the current code renders. When
    /// this fails the config surface changed without regenerating the file.
    #[cfg(all(feature = "bedrock", feature = "openai-responses", feature = "gemini"))]
    #[test]
    fn committed_schema_matches_render() {
        let committed = include_str!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../routectl.schema.json"
        ));
        assert_eq!(
            committed,
            render_schema_json(),
            "routectl.schema.json is stale -- run `cargo run --bin gen_schema` and commit the result"
        );
    }

    #[test]
    fn render_is_deterministic() {
        assert_eq!(render_schema_json(), render_schema_json());
    }

    /// The rendered schema must carry no generating machine's home path. Path
    /// defaults resolve `HOME` / `XDG_CONFIG_HOME` at generation time; a
    /// re-introduced absolute default would ship a personal path in the
    /// committed artifact and make the golden test box-dependent.
    #[test]
    fn render_carries_no_home_path() {
        let rendered = render_schema_json();
        for needle in ["/home/", "/root/", "/Users/"] {
            assert!(
                !rendered.contains(needle),
                "rendered schema must not embed a machine home path, found `{needle}`"
            );
        }
    }

    #[test]
    fn root_carries_version_and_generated_markers() {
        let value: serde_json::Value =
            serde_json::from_str(&render_schema_json()).expect("rendered schema parses");

        assert_eq!(
            value.pointer(&format!("/{VERSION_KEY}")),
            Some(&serde_json::Value::from(CURRENT_CONFIG_VERSION)),
            "root must carry the config-version metadata"
        );
        assert_eq!(
            value
                .pointer(&format!("/{GENERATED_KEY}"))
                .and_then(serde_json::Value::as_str),
            Some(GENERATED_MARKER),
            "root must carry the @generated marker"
        );
        assert!(
            value
                .pointer(&format!("/{GENERATED_KEY}"))
                .and_then(serde_json::Value::as_str)
                .is_some_and(|s| s.contains("@generated")),
            "the generated marker must contain `@generated`"
        );
    }

    /// `class_overrides` is a `BTreeMap<u16, _>` that serializes with STRING
    /// keys; the `#[schemars(with)]` override must keep the RENDERED schema a
    /// string-keyed object of `ConfigFailureClass`, never a u16 map.
    #[test]
    fn class_overrides_renders_string_keyed() {
        let value: serde_json::Value =
            serde_json::from_str(&render_schema_json()).expect("rendered schema parses");

        let arms = value
            .pointer("/$defs/ProviderEntry/oneOf")
            .and_then(serde_json::Value::as_array)
            .expect("ProviderEntry renders as a oneOf of tagged variants");

        let mut seen = 0usize;
        for arm in arms {
            let Some(field) = arm.pointer("/properties/class_overrides") else {
                continue;
            };
            seen += 1;
            assert_eq!(
                field.pointer("/type").and_then(serde_json::Value::as_str),
                Some("object"),
                "class_overrides must be a string-keyed object, got: {field}"
            );
            assert_eq!(
                field
                    .pointer("/additionalProperties/$ref")
                    .and_then(serde_json::Value::as_str),
                Some("#/$defs/ConfigFailureClass"),
                "class_overrides values must reference ConfigFailureClass, got: {field}"
            );
        }
        assert!(
            seen > 0,
            "class_overrides must surface on at least one provider variant"
        );
    }
}
